### obtain new token (which will expire and new refresh token
POST  http://localhost:4000/login
Content-Type: application/json

{
   "name":"Nina"
}
### obtain new token using refresh token
POST http://localhost:4000/token 
Content-Type: application/json

{
   "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmluYSIsImlhdCI6MTcxNTE3NDM0MX0.zNZl6eg6L5IpjB7gJ5Yfbzz18A_O47Njsp-Wstnxgvw"
}

###get the posts using token
GET http://localhost:3000/posts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmluYSIsImlhdCI6MTcxNTE3NDAyNSwiZXhwIjoxNzE1MTc0MjI1fQ.5bofmrV49wTTY19KqDKEyDPdG-5OM83EdqfpwIbhpBE 

###logout --> eliminate refresh tokens
DELETE  http://localhost:4000/logout
Content-Type: application/json

{
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmluYSIsImlhdCI6MTcxNTE3NDM0MX0.zNZl6eg6L5IpjB7gJ5Yfbzz18A_O47Njsp-Wstnxgvw"
}
