version: '3.8'

services:
  frontend:
    build:
      context: ./PaintingSuppliesFrontend
      dockerfile: Dockerfile
    ports: 
      - '3000:80'
    networks:
      - web
    depends_on:
      - api1
      - api2

  api1:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      ACCESS_TOKEN_SECRET: '1080dc7dc6b87d2d4ad6cd6b7766365a008c8da4f7d1c808ec0c7babd5a6f32fde8349bca68e80dd2672fc1b0702557d8a7d60ca3d174d54e7df1b9bf9505a99'
      REFRESH_TOKEN_SECRET: '1080dc7dc6b87d2d4ad6cd6b7766365a008c8da4f7d1c808ec0c7babd5a6f32fde8349bca68e80dd2672fc1b0702557d8a7d60ca3d174d54e7df1b9bf9505a89'
    ports:
      - '5001:5001'
    depends_on:
      - mysql
    volumes:
      - ./Backend:/app
    networks:
      - web
    command: npm start 

  api2:
    build:
      context: ./PaintingsuppliesBackend
      dockerfile: Dockerfile
    environment:
      ACCESS_TOKEN_SECRET: '1080dc7dc6b87d2d4ad6cd6b7766365a008c8da4f7d1c808ec0c7babd5a6f32fde8349bca68e80dd2672fc1b0702557d8a7d60ca3d174d54e7df1b9bf9505a99'
      REFRESH_TOKEN_SECRET: '1080dc7dc6b87d2d4ad6cd6b7766365a008c8da4f7d1c808ec0c7babd5a6f32fde8349bca68e80dd2672fc1b0702557d8a7d60ca3d174d54e7df1b9bf9505a89'
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    volumes:
      - ./PaintingsuppliesBackend:/app
    networks:
      - web
    command: npm start   



  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'Capsunica2003'
      MYSQL_DATABASE: 'supplies'
    volumes: 
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - web

volumes:
  mysql-data:

networks:
  web:
    driver: bridge
